### ISSUE TITLE
The speed of generating data with mimicgen

### ISSUE THREAD

**Issue by xuanshao27** [robocasa/robocasa#112]
Thank you for your apply last time,I can use your code to generate my data now,but I the speed is very slow, and it is seems like that it doesn't use GPU.

Is there any way to make it faster?

Besides,It will cost half an hour to get 158 trials and the successful rate is a little low, what can I do to improve the successful rate?
 
**************************************************
trial 158 success: False
have 40 successes out of 158 trials so far
have 118 failures out of 158 trials so far
**************************************************

**Comment by snasiriany** [comment]
It is not expected to use GPU, since GPU is only for rendering purposes, and MimicGen just runs rollouts with MuJoCo without rendering, which is CPU based.

A solution would be to parallelize the script with subprocesses. We don't have a clean script for this right now. Can you post this issue on the MimicGen page? https://github.com/NVlabs/mimicgen. I will close it here for now as this is more general to MimicGen.

We can try to help out there.
