### ISSUE TITLE
How to add other third-person cameras

### ISSUE THREAD

**Issue by BoyuLi-XH** [robocasa/robocasa#113]
Thanks for the issue[https://github.com/robocasa/robocasa/issues/18](url). I run 
```
python ./robocasa/scripts/collect_demos.py --debug --env PrepareCoffee --robots GR1FixedLowerBody
```
successfully. But after I changed the robots to H1, the robot third person camera input is inappropriate, which is shown below.
![wechat_2024-12-18_185910_307](https://github.com/user-attachments/assets/8773184f-9482-4f7c-bd43-a0d569dfede8)
This is the camera named "robot0_agentview_center". Other cameras such as 'robot0_agentview_left', 'robot0_agentview_right', 'robot0_frontview', 'robot0_eye_in_hand' cannot observe the whole robot state. How can I add a suitable third-person camera?

**Comment by BoyuLi-XH** [comment]
Another question: Is there any control policy or language skill that I can control the humanoid robot to move or interact with the objects?

**Comment by BoyuLi-XH** [comment]
Hope to get your reply @snasiriany

**Comment by snasiriany** [comment]
Hi @BoyuLi-XH this is because the camera settings may need to be adjusted for each different robot. Go into this file: https://github.com/robocasa/robocasa/blob/45eb87eaca84eaac1d3ac0185338fc10bbe1554f/robocasa/utils/camera_utils.py#L94-L95

And add a section for the H1 robot with any camera adjustments that suit your case.

> Another question: Is there any control policy or language skill that I can control the humanoid robot to move or interact with the objects?
We provide datasets and policy learning code, which you can use to learn some language conditioned policies. Please see our documentation page for more information: https://robocasa.ai/docs/introduction/overview.html
