### ISSUE TITLE
Method to keep oobjects consistent each time the environment is initialized

### ISSUE THREAD

**Issue by KaiyuHu2001** [robocasa/robocasa#91]
Some objects in the environment have their types and positions randomly generated. Is there a way to keep them consistent each time the environment is initialized?

**Comment by snasiriany** [comment]
By design, we want to include randomization, but we do allow seed'ing environments, so that the environment resets are deterministic everytime you create and use an environment. See here: https://github.com/robocasa/robocasa/blob/0d34893fdaf62d2b2a112908bafa37880b4c5011/robocasa/environments/kitchen/kitchen.py#L219

In addition, we offer the ability to play back existing demonstrations with exactly the same type of objects and randomized positions that were used in the original demos: https://robocasa.ai/docs/datasets/using_datasets.html#inspecting-and-visualizing-datasets

**Comment by snasiriany** [comment]
One thing to add: you can specify the exact path to a specific object that you want to sample, instead of a broad category, see here: https://github.com/robocasa/robocasa/blob/0d34893fdaf62d2b2a112908bafa37880b4c5011/robocasa/models/objects/kitchen_object_utils.py#L174
