### ISSUE TITLE
[Errno 2] No such file or directory: '/robocasa/robocasa/models/assets/fixtures/fixture_registry/wall.yaml'

### ISSUE THREAD

**Issue by dzy666fly** [robocasa/robocasa#95]
Thank u so much for sharing this wonderful work.

After installing the environment, I began to try the command `python -m robocasa.demos.demo_kitchen_scenes`. Then something went wrong as follows:
```
[Errno 2] No such file or directory: '/robocasa/robocasa/models/assets/fixtures/fixture_registry/wall.yaml'
```

Well, because of the network disconnection when running `python robocasa/scripts/download_kitchen_assets.py `, I downloaded the assets directly from URL from the  `download_kitchen_assets.py` and then unzip them one by one.
The size of each one is shown in the picture.
![Screenshot from 2024-10-17 15-13-29](https://github.com/user-attachments/assets/ac57a88c-963d-4073-8004-fa07ea5ad119)

Maybe, I guess, owing to the way of downloading assets?

And how can I solve this error?

Thank u so much.

**Comment by snasiriany** [comment]
Ah, thanks for letting us know! This is because we recently changed the file structures for fixtures. I just pushed to `main` branch with the change: https://github.com/robocasa/robocasa/commit/84e0b7ad48d4bd3f1c2760af42a239af340e369c

If you pull the latest and try again, hopefully should work now.
